import frappe

def update_parent_accounts():
    # List of accounts to update with their new parent accounts
    accounts_to_update = [
        # {"account_name": "11901 AccDepAdmBuildTechInstal - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11900 - AccDepAdmBuildStructure - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11902 - AccDepAdmBuildTeleAut - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11906 - AccDepOtherOperBuildStructure - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11907 - AccDepOtherOperBuildTechInstal - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11908 - AccDepOtherOperBuildTeleAut - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11920 - AccDepDamInstal - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11921 - AccDepTunnelSystem - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11922 - AccDepRockRoom - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11923 - AccDepRoadBridgeQuay - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11930 - AccDepPipeLine - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11931 - AccDepMechEquipWaterPath - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11932 - AccDepTurbine - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11933 - AccDepOtherMachineTechPart - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11940 - AccDepGeneratorPrimaryPart - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11941 - AccDepTransformerSecondaryPart - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11942 - AccDepSwitchGearHighVolt - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11943 - AccDepControlGear - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11944 - AccDepElectroTechAuxGear - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11945 - AccDepSystemControlCentre - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "11946 - AccDepTelecommCircuit - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12900 - AccDepMachinery - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12940 - AccDepMeansTransport - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12950 - AccDepFurniture - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12960 - AccDepPermBuildFixture - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12970 - AccDepTool - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12980 - AccDepComputerHardware - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12981 - AccDepComputerSoftware - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12982 - AccDepOfficeMachine - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12983 - AccDepElectricAppliances - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12984 - AccDepPhones/PhoneSystems - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12985 - AccDepOtherOfficeEquip - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        # {"account_name": "12990 - AccDepOtherFixedAsset - HPL", "new_parent_account": "1780 - Accumulated Depreciation - HPL"},
        {"account_name": "19000N PettyCash/NPR Kathmandu (N) - HPL", "new_parent_account": "11000 - Cash In Hand - HPL"},
        {"account_name": "19201N SCB/NPR 01-0417289-01 CUR  (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19201N SCB/NPR 01-0417289-01 CUR  (N)(GBP) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19201N SCB/NPR 01-0417289-01 CUR (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19212N NMB/NPR0200010920300012 CUR  (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19213N NMB/NPR 0200010920300038 CUR  (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19213N NMB/NPR 0200010920300038 CUR (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "19218N EBL/NPR 03500105200628 CUR  (N) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"},
        {"account_name": "12100 FixedAssetUnderConstruction - HPL", "new_parent_account": "12100 - Capital WIP Account - HPL"},
        {"account_name": "15700 OtherShortTermReceiv - HPL", "new_parent_account": "13500 - Other Current Asset - HPL "},
        {"account_name": "17000 PrepaidExpenses - HPL", "new_parent_account": "13500 - Other Current Asset - HPL "},
        {"account_name": "19601 DepositNPR - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "29900 OtherShortTermLiab - HPL", "new_parent_account": "23200 - Other Current Liability - HPL"},
        {"account_name": "29901 InventoryReceivedNotBilled - HPL", "new_parent_account": "29901 InventoryReceivedNotBilled"},
        {"account_name": "12700 Tool - HPL", "new_parent_account": "11200 - Capital Equipments - HPL"},
        {"account_name": "12800 ComputerHardware - HPL", "new_parent_account": "17000 - Fixed Assets - HPL"},
        {"account_name": "12801 ComputerSoftware - HPL", "new_parent_account": "12800 - Softwares - HPL"},
        {"account_name": "12802 OfficeMachine - HPL", "new_parent_account": "11301 - Plants and Machineries - HPL"},
        {"account_name": "12803 ElectricAppliances - HPL", "new_parent_account": "17000 - Fixed Assets - HPL"},
        {"account_name": "12804 Phones/PhoneSystems - HPL", "new_parent_account": "12803 - Electronic Equipments - HPL"},
        {"account_name": "12805 OtherOfficeEquip - HPL", "new_parent_account": "128005 - Office Equipments - HPL"},
        {"account_name": "12809 OtherFixedAsset - HPL", "new_parent_account": "12808 - OtherFixedAsset - HPL"},
        {"account_name": "14000 RawMaterialSemiManufacture - HPL", "new_parent_account": "14000 - Stock Assets - HPL"},
        {"account_name": "15600 ShortTermReceivEmployee - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "15603 PrepaidCardCashAdvEmployee - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "15605 CashAdvanceEmployee.NPR - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16000 PrepaidSupplier - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16000 PrepaidSupplier(EUR) - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16000 PrepaidSupplier(GBP) - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16000 PrepaidSupplier(INR) - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16000 PrepaidSupplier(USD) - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16100 VATInput USD - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16800 WithheldTaxAdvanceTax - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"},
        {"account_name": "16800 WithheldTaxAdvanceTax(USD) - HPL", "new_parent_account": "13500 - Other Current Asset - HPL"}, 
        {"account_name": "17600 AccruedInterestIncome - HPL", "new_parent_account": "42000 - Other Income - HPL"}, 
        {"account_name": "19200N SCB/USD 01-0417319-51 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19201N SCB/NPR 01-0417289-01 CUR  (N)(EUR) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19201N SCB/NPR 01-0417289-01 CUR  (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19211N SCB/USD 01-1107496-53 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19212N NMB/NPR0200010920300012 CUR  (N)(EUR) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19212N NMB/NPR0200010920300012 CUR  (N)(GBP) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19212N NMB/NPR0200010920300012 CUR  (N)(INR) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19212N NMB/NPR0200010920300012 CUR  (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19216N EBL/USD 03500105200629 CUR  (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19217N NIBL/USD 01201010250443 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19219N SBL/USD 00100010083 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19220N NMB/USD 0010010920300053 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19300N NSBI/USD 20238400100005 CUR (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        {"account_name": "19600 DepositUSD - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "19600 DepositUSD(EUR) - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "19600 DepositUSD(USD) - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "19610 DepositForLetterOfCredit - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "19610 DepositForLetterOfCredit(USD) - HPL", "new_parent_account": "13900 - Securities and Deposits - HPL"}, 
        {"account_name": "19660N FixedDeposits EBL (N)(USD) - HPL", "new_parent_account": "19400 - Bank Accounts - HPL"}, 
        # {"account_name": "Account 3", "new_parent_account": "51000 - Direct Expenses - HPL"},
        # {"account_name": "Account 3", "new_parent_account": "51000 - Direct Expenses - HPL"},
         
    ]

    # Loop through each account and update the parent account
    for account_data in accounts_to_update:
        try:
            account = frappe.get_doc("Account", account_data["account_name"])
            account.parent_account = account_data["new_parent_account"]
            account.save()
            print(f"Successfully updated parent account for {account_data['account_name']}")
        except Exception as e:
            frappe.log_error(message=str(e), title="Failed to update parent account")
            print(f"Error updating {account_data['account_name']}: {e}")

    # Commit the changes to the database
    frappe.db.commit()
